const CHARACTER_SFX_URL = '/fighting-game/assets/sound/bg/08 - DavidKBD - Belmont Chronicles Pack - The Dungeons.ogg';

export const CHARACTER_CONFIG = {
  hero: {
    id: 'samurai-mack',
    scale: 2.5,
    spawn: {
      x: 260,
      y: 560,
    },
    controls: {
      moveDeadZone: 0.2,
      runThreshold: 8,
    },
    physics: {
      moveSpeed: 260,
      jumpVelocity: 620,
      dragX: 2200,
      maxVelocityX: 420,
      maxVelocityY: 1400,
      body: {
        width: 70,
        height: 120,
        offsetX: 62,
        offsetY: 80,
      },
    },
    timing: {
      attackCooldownMs: 350,
      hitRecoverMs: 280,
    },
    assets: {
      sprites: {
        idle: {
          key: 'samurai-mack-idle',
          url: '/fighting-game/assets/sprites/samuraiMack/Idle.png',
          frame: { width: 200, height: 200 },
        },
        run: {
          key: 'samurai-mack-run',
          url: '/fighting-game/assets/sprites/samuraiMack/Run.png',
          frame: { width: 200, height: 200 },
        },
        jump: {
          key: 'samurai-mack-jump',
          url: '/fighting-game/assets/sprites/samuraiMack/Jump.png',
          frame: { width: 200, height: 200 },
        },
        fall: {
          key: 'samurai-mack-fall',
          url: '/fighting-game/assets/sprites/samuraiMack/Fall.png',
          frame: { width: 200, height: 200 },
        },
        attack: {
          key: 'samurai-mack-attack',
          url: '/fighting-game/assets/sprites/samuraiMack/Attack1.png',
          frame: { width: 200, height: 200 },
        },
        hit: {
          key: 'samurai-mack-hit',
          url: '/fighting-game/assets/sprites/samuraiMack/Take Hit.png',
          frame: { width: 200, height: 200 },
        },
        death: {
          key: 'samurai-mack-death',
          url: '/fighting-game/assets/sprites/samuraiMack/Death.png',
          frame: { width: 200, height: 200 },
        },
      },
      actionSfx: {
        jump: {
          key: 'sfx-character-jump',
          url: CHARACTER_SFX_URL,
          channel: 'sfx',
          allowMultiple: false,
          restartIfPlaying: true,
        },
        attack: {
          key: 'sfx-character-attack',
          url: CHARACTER_SFX_URL,
          channel: 'sfx',
          allowMultiple: true,
        },
        hit: {
          key: 'sfx-character-hit',
          url: CHARACTER_SFX_URL,
          channel: 'sfx',
          allowMultiple: true,
        },
        death: {
          key: 'sfx-character-death',
          url: CHARACTER_SFX_URL,
          channel: 'sfx',
          allowMultiple: false,
        },
        run: {
          key: 'sfx-character-run',
          url: CHARACTER_SFX_URL,
          channel: 'sfx',
          allowMultiple: false,
        },
        idle: {
          key: 'sfx-character-idle',
          url: CHARACTER_SFX_URL,
          channel: 'sfx',
          allowMultiple: false,
        },
        fall: {
          key: 'sfx-character-fall',
          url: CHARACTER_SFX_URL,
          channel: 'sfx',
          allowMultiple: false,
        },
      },
    },
    animations: {
      idle: {
        key: 'samurai-mack-anim-idle',
        texture: 'samurai-mack-idle',
        startFrame: 0,
        endFrame: 7,
        frameRate: 11,
        repeat: -1,
      },
      run: {
        key: 'samurai-mack-anim-run',
        texture: 'samurai-mack-run',
        startFrame: 0,
        endFrame: 7,
        frameRate: 13,
        repeat: -1,
      },
      jump: {
        key: 'samurai-mack-anim-jump',
        texture: 'samurai-mack-jump',
        startFrame: 0,
        endFrame: 1,
        frameRate: 10,
        repeat: 0,
      },
      fall: {
        key: 'samurai-mack-anim-fall',
        texture: 'samurai-mack-fall',
        startFrame: 0,
        endFrame: 1,
        frameRate: 10,
        repeat: -1,
      },
      attack: {
        key: 'samurai-mack-anim-attack',
        texture: 'samurai-mack-attack',
        startFrame: 0,
        endFrame: 5,
        frameRate: 14,
        repeat: 0,
      },
      hit: {
        key: 'samurai-mack-anim-hit',
        texture: 'samurai-mack-hit',
        startFrame: 0,
        endFrame: 3,
        frameRate: 12,
        repeat: 0,
      },
      death: {
        key: 'samurai-mack-anim-death',
        texture: 'samurai-mack-death',
        startFrame: 0,
        endFrame: 5,
        frameRate: 9,
        repeat: 0,
      },
    },
  },
  enemy: {
    id: 'kenji',
    scale: 2.4,
    spawn: {
      x: 980,
      y: 560,
    },
    controls: {
      moveDeadZone: 0.2,
      runThreshold: 8,
    },
    physics: {
      moveSpeed: 210,
      jumpVelocity: 600,
      dragX: 2200,
      maxVelocityX: 380,
      maxVelocityY: 1400,
      body: {
        width: 65,
        height: 120,
        offsetX: 66,
        offsetY: 80,
      },
    },
    timing: {
      attackCooldownMs: 420,
      hitRecoverMs: 320,
    },
    assets: {
      sprites: {
        idle: {
          key: 'kenji-idle',
          url: '/fighting-game/assets/sprites/kenji/Idle.png',
          frame: { width: 200, height: 200 },
        },
        run: {
          key: 'kenji-run',
          url: '/fighting-game/assets/sprites/kenji/Run.png',
          frame: { width: 200, height: 200 },
        },
        jump: {
          key: 'kenji-jump',
          url: '/fighting-game/assets/sprites/kenji/Jump.png',
          frame: { width: 200, height: 200 },
        },
        fall: {
          key: 'kenji-fall',
          url: '/fighting-game/assets/sprites/kenji/Fall.png',
          frame: { width: 200, height: 200 },
        },
        attack: {
          key: 'kenji-attack',
          url: '/fighting-game/assets/sprites/kenji/Attack1.png',
          frame: { width: 200, height: 200 },
        },
        hit: {
          key: 'kenji-hit',
          url: '/fighting-game/assets/sprites/kenji/Take hit.png',
          frame: { width: 200, height: 200 },
        },
        death: {
          key: 'kenji-death',
          url: '/fighting-game/assets/sprites/kenji/Death.png',
          frame: { width: 200, height: 200 },
        },
      },
      actionSfx: {
        jump: {
          key: 'sfx-enemy-jump',
          url: CHARACTER_SFX_URL,
          channel: 'sfx',
          allowMultiple: false,
          restartIfPlaying: true,
        },
        attack: {
          key: 'sfx-enemy-attack',
          url: CHARACTER_SFX_URL,
          channel: 'sfx',
          allowMultiple: true,
        },
        hit: {
          key: 'sfx-enemy-hit',
          url: CHARACTER_SFX_URL,
          channel: 'sfx',
          allowMultiple: true,
        },
        death: {
          key: 'sfx-enemy-death',
          url: CHARACTER_SFX_URL,
          channel: 'sfx',
          allowMultiple: false,
        },
      },
    },
    animations: {
      idle: {
        key: 'kenji-anim-idle',
        texture: 'kenji-idle',
        startFrame: 0,
        endFrame: 3,
        frameRate: 8,
        repeat: -1,
      },
      run: {
        key: 'kenji-anim-run',
        texture: 'kenji-run',
        startFrame: 0,
        endFrame: 7,
        frameRate: 12,
        repeat: -1,
      },
      jump: {
        key: 'kenji-anim-jump',
        texture: 'kenji-jump',
        startFrame: 0,
        endFrame: 1,
        frameRate: 10,
        repeat: 0,
      },
      fall: {
        key: 'kenji-anim-fall',
        texture: 'kenji-fall',
        startFrame: 0,
        endFrame: 1,
        frameRate: 10,
        repeat: -1,
      },
      attack: {
        key: 'kenji-anim-attack',
        texture: 'kenji-attack',
        startFrame: 0,
        endFrame: 3,
        frameRate: 14,
        repeat: 0,
      },
      hit: {
        key: 'kenji-anim-hit',
        texture: 'kenji-hit',
        startFrame: 0,
        endFrame: 2,
        frameRate: 12,
        repeat: 0,
      },
      death: {
        key: 'kenji-anim-death',
        texture: 'kenji-death',
        startFrame: 0,
        endFrame: 6,
        frameRate: 9,
        repeat: 0,
      },
    },
  },
};
